export const COUNTRIES = ['Afghanistan','Afrique du Sud','Albanie','Algérie','Allemagne','Andorre','Angola',
  'Antigua et Barbuda','Arabie saoudite','Argentine','Arménie','Australie','Autriche','Azerbaïdjan','Bahamas',
  'Bahrein','Bangladesh','Barbade','Belgique','Bélize','Benin','Bhoutan','Biélorussie','Bolivie',
  'Bosnie-Herzégovine','Botswana','Brésil','Brunei','Bulgarie','Burkina Faso','Burundi','Cambodge','Cameroun',
  'Canada','Cap Vert','Centrafrique','Chili','Chine','Chypre','Colombie','Comores', 'Congo démocratique','Congo',
  'Corée du Nord','Corée du Sud','Costa Rica','Côte dIvoire','Croatie','Cuba','Danemark','Djibouti','Dominique',
  'RépubliqueDominicaine','Egypte','Emirats Arabes Unis','Equateur','Erythrée','Espagne','Estonie','Etats-Unis',
  'Ethiopie','Fidji','Finlande','France','Gabon','Gambie','Géorgie','Ghana','Grèce','Grenade','Groenland',
  'Guatémala','Guinée','Guinée Bissau','Guinée équatoriale','Guyana','Haïti','Honduras','Hong Kong','Hongrie',
  'Inde','Indonésie','Irak','Iran','Irlande','Islande','Israël','Italie','Jamaïque','Japon','Jordanie','Kazakhstan',
  'Kenya','Kirghizstan','Kiribati','Koweït','Laos','Lesotho','Lettonie','Liban','Liberia','Libye','Liechtenstein',
  'Lituanie','Luxembourg','Macédoine','Madagascar','Malaisie','Malawi','Maldives','Mali','Malte','Maroc','Marshall',
  'Maurice','Mauritanie','Mexique','Micronésie','Moldavie','Monaco','Mongolie','Mozambique','Myanmar','Namibie',
  'Népal','Nicaragua','Niger','Nigeria','Norvège','Nouvelle Zélande','Oman','Ouganda','Ouzbekistan','Pakistan',
  'Palau','Palestine','Panama','Papouasie - Nouvelle Guinée','Paraguay','Pays-Bas','Pérou','Philippines','Pologne',
  'Porto Rico','Portugal','Qatar','Roumanie','Royaume-Uni','Russie','Rwanda','Saint Christophe et Nevis',
  'Saint Vincent et les Grenadines','Sainte Lucie','Salomon','Salvador','Samoa','São Tomé et Príncipe','Sénégal',
  'Seychelles','Sierra Leone','Singapour','Slovaquie','Slovénie','Somalie','Somaliland','Soudan','Sri Lanka',
  'Suède','Suisse','Surinam','Syrie','Swaziland','Tadjikistan','Taïwan','Tanzanie','Tchad','Tchéquie',
  'Thaïlande','Tibet','Timor Oriental','Togo','Tonga','Trinité et Tobago','Tunisie','Turkmenistan',
  'Turquie','Tuvalu','Ukraine','Uruguay','Vanuatu','Vatican','Vénézuéla','Vietnam','Yémen','Yougoslavie',
  'Zambie','Zimbabwe'];
